spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO  }
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  output:
    ansi:
      enabled: ALWAYS

  server:
    error:
      include-message: always

  logging:
    level.com.LPC.user_service: DEBUG

  kafka:
    bootstrap-servers: localhost:9092
    admin.auto-create: true

    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer.group-id: ${spring.application.name}
    consumer.auto-offset-reset: earliest
    consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    properties:
      spring:
        deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        json.trusted.packages: com.lpc.upload.dto
